# Generated by Django 4.1.4 on 2023-05-15 10:41

from django.db import migrations, models
import django.db.models.deletion
import galleries.models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'hide'), (3, 'published')], default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, posts.models.CheckAgeMixin),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to=galleries.models.upload_to)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'hide'), (3, 'published')], default=1)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.gallery')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, posts.models.CheckAgeMixin),
        ),
    ]
