# Generated by Django 4.1.4 on 2023-04-25 10:00

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_created_book_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('birth_day', models.IntegerField()),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('biogram', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, posts.models.CheckAgeMixin),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.author'),
        ),
    ]
