# Generated by Django 4.1.4 on 2023-04-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
